#include "webui_api.h"

const char *webui_get_index_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>VL53L1x Configuration</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".navbar-nav li.sensor-nav-item { display: none; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".row { display: flex; flex-wrap: wrap; margin: 0 -10px; }"
           ".col-md-6 { flex: 0 0 50%; max-width: 50%; padding: 0 10px; }"
           ".col-md-4 { flex: 0 0 33.333333%; max-width: 33.333333%; padding: 0 10px; }"
           "@media (max-width: 768px) { .col-md-6, .col-md-4 { flex: 0 0 100%; max-width: 100%; } }"
           ".form-group { margin-bottom: 20px; }"
           "label { font-weight: 600; color: #555; display: block; margin-bottom: 5px; }"
           ".form-control { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; }"
           ".form-control:focus { border-color: #80bdff; outline: 0; box-shadow: 0 0 0 0.2rem rgba(0,123,255,0.25); }"
           ".btn { display: inline-block; padding: 8px 16px; font-size: 14px; font-weight: 400; text-align: center; cursor: pointer; border: 1px solid transparent; border-radius: 4px; text-decoration: none; }"
           ".btn-primary { color: #fff; background-color: #007bff; border-color: #007bff; }"
           ".btn-primary:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".btn-secondary { color: #fff; background-color: #6c757d; border-color: #6c757d; }"
           ".btn-secondary:hover { background-color: #5a6268; border-color: #545b62; }"
           ".btn-warning { color: #212529; background-color: #ffc107; border-color: #ffc107; }"
           ".btn-warning:hover { background-color: #e0a800; border-color: #d39e00; }"
           ".alert { position: relative; padding: 12px 20px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }"
           ".alert-success { color: #155724; background-color: #d4edda; border-color: #c3e6cb; }"
           ".alert-danger { color: #721c24; background-color: #f8d7da; border-color: #f5c6cb; }"
           ".alert-warning { color: #856404; background-color: #fff3cd; border-color: #ffeaa7; }"
           ".alert-info { color: #0c5460; background-color: #d1ecf1; border-color: #bee5eb; }"
           ".input-group { display: flex; align-items: stretch; }"
           ".input-group .form-control { flex: 1 1 auto; }"
           ".input-group .btn { margin-left: 5px; }"
           ".btn-group { margin-top: 30px; }"
           ".status-card { border: 1px solid #ddd; border-radius: 8px; padding: 0; margin-bottom: 20px; background-color: #fff; overflow: hidden; }"
           ".card-header { background-color: #f8f9fa; padding: 15px 20px; border-bottom: 1px solid #dee2e6; margin: 0; }"
           ".card-header h2 { margin: 0; color: #212529; font-size: 1.25rem; font-weight: 600; }"
           ".card-body { padding: 20px; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\" class=\"active\">Configuration</a></li>"
           "<li class=\"sensor-nav-item\"><a href=\"/vl53l1x\">VL53L1x</a></li>"
           "<li><a href=\"/inputassembly\">T->O</a></li>"
           "<li><a href=\"/outputassembly\">O->T</a></li>"
           "<li><a href=\"/ota\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>Configuration</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div class=\"status-card\" style=\"margin-bottom: 30px;\">"
           "<div class=\"card-header\">"
           "<h2>Network Configuration</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<form id=\"ipconfigForm\">"
           "<div class=\"form-group\">"
           "<label style=\"display: flex; align-items: center; cursor: pointer;\">"
           "<input type=\"checkbox\" id=\"use_dhcp\" name=\"use_dhcp\" style=\"margin-right: 8px; width: auto; cursor: pointer;\">"
           "<span>Use DHCP (Automatic IP Assignment)</span>"
           "</label>"
           "</div>"
           "<div style=\"margin-bottom: 20px; padding: 12px; background-color: #f8f9fa; border-left: 4px solid #007bff; border-radius: 4px;\">"
           "<p style=\"margin: 0; color: #495057; font-size: 14px; line-height: 1.6;\">"
           "<strong>Network Settings:</strong> Configure the device's IP address and network parameters. "
           "These settings are stored in OpENer's NVS and control both EtherNet/IP and Modbus TCP connectivity. "
           "When DHCP is enabled, the device automatically obtains network settings from your router. "
           "For static IP configuration, ensure the IP address, netmask, and gateway are compatible with your network. "
           "A device reboot is required for network changes to take effect."
           "</p>"
           "</div>"
           "<div id=\"staticIpFields\" style=\"display: none;\">"
           "<div class=\"row\">"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>IP Address</label>"
           "<input type=\"text\" class=\"form-control\" id=\"ip_address\" name=\"ip_address\" placeholder=\"192.168.1.100\" pattern=\"^([0-9]{1,3}\\.){3}[0-9]{1,3}$\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>Netmask</label>"
           "<input type=\"text\" class=\"form-control\" id=\"netmask\" name=\"netmask\" placeholder=\"255.255.255.0\" pattern=\"^([0-9]{1,3}\\.){3}[0-9]{1,3}$\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>Gateway</label>"
           "<input type=\"text\" class=\"form-control\" id=\"gateway\" name=\"gateway\" placeholder=\"192.168.1.1\" pattern=\"^([0-9]{1,3}\\.){3}[0-9]{1,3}$\">"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           "<div id=\"dnsFields\" style=\"display: none;\">"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Primary DNS</label>"
           "<input type=\"text\" class=\"form-control\" id=\"dns1\" name=\"dns1\" placeholder=\"8.8.8.8\" pattern=\"^([0-9]{1,3}\\.){3}[0-9]{1,3}$\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Secondary DNS</label>"
           "<input type=\"text\" class=\"form-control\" id=\"dns2\" name=\"dns2\" placeholder=\"8.8.4.4\" pattern=\"^([0-9]{1,3}\\.){3}[0-9]{1,3}$\">"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveIpConfig()\">Save Network Configuration</button>"
           "<span style=\"margin-left: 10px; color: #666; font-size: 12px;\">(Reboot required to apply changes)</span>"
           "</form>"
           "</div>"
           "</div>"
           "<div class=\"status-card\" style=\"margin-top: 30px;\">"
           "<div class=\"card-header\">"
           "<h2>Modbus TCP</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<form id=\"modbusForm\">"
           "<div class=\"form-group\">"
           "<label style=\"display: flex; align-items: center; cursor: pointer;\">"
           "<input type=\"checkbox\" id=\"modbus_enabled\" name=\"modbus_enabled\" style=\"margin-right: 8px; width: auto; cursor: pointer;\">"
           "<span>Enable Modbus TCP Server (Port 502)</span>"
           "</label>"
           "</div>"
           "<div style=\"margin-top: 15px; margin-bottom: 15px; padding: 12px; background-color: #f8f9fa; border-left: 4px solid #007bff; border-radius: 4px;\">"
           "<p style=\"margin: 0; color: #495057; font-size: 14px; line-height: 1.6;\">"
           "<strong>Data Mapping:</strong> The Modbus TCP server provides read-write access to the same data structures used by EtherNet/IP. "
           "Input Registers 0-15 mirror the Input Assembly 100 (sensor readings including distance, status, ambient light, and signal strength), "
           "while Holding Registers 100-115 mirror the Output Assembly 150 (32 bytes of control data). "
           "All data is synchronized in real-time between Modbus TCP and EtherNet/IP protocols."
           "</p>"
           "</div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveModbusConfig()\">Save Modbus Configuration</button>"
           "</form>"
           "</div>"
           "</div>"
           "<div class=\"status-card\" style=\"margin-top: 30px;\">"
           "<div class=\"card-header\">"
           "<h2>VL53L1x Sensor Configuration</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<form id=\"sensorConfigForm\">"
           "<div class=\"form-group\">"
           "<label style=\"display: flex; align-items: center; cursor: pointer;\">"
           "<input type=\"checkbox\" id=\"sensor_enabled\" name=\"sensor_enabled\" style=\"margin-right: 8px; width: auto; cursor: pointer;\">"
           "<span>Enable VL53L1x Sensor</span>"
           "</label>"
           "</div>"
           "<div style=\"margin-top: 15px; margin-bottom: 15px; padding: 12px; background-color: #f8f9fa; border-left: 4px solid #007bff; border-radius: 4px;\">"
           "<p style=\"margin: 0; color: #495057; font-size: 14px; line-height: 1.6;\">"
           "<strong>Time-of-Flight Sensor:</strong> The VL53L1x is a high-precision distance measurement sensor using time-of-flight technology. "
           "Configure measurement parameters such as distance mode (SHORT for <1.3m, LONG for <4m), timing budget, and region of interest (ROI). "
           "Calibration values (offset and crosstalk) improve accuracy for your specific application. "
           "All settings are saved to NVS and persist across reboots. Changes take effect immediately after saving."
           "</p>"
           "</div>"
           "<div class=\"form-group\" style=\"margin-top: 20px;\">"
           "<label>Sensor Data Byte Range</label>"
           "<select class=\"form-control\" id=\"sensor_byte_range\" name=\"sensor_byte_range\">"
           "<option value=\"0\">Bytes 0-8</option>"
           "<option value=\"9\">Bytes 9-17</option>"
           "<option value=\"18\">Bytes 18-26</option>"
           "</select>"
           "<small style=\"display: block; margin-top: 5px; color: #6c757d;\">Select the byte range in Input Assembly 100 where sensor data will be written (9 bytes total)</small>"
           "</div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveSensorConfig()\">Save Sensor Configuration</button>"
           "<div id=\"sensorSettingsFields\">"
           "<div style=\"margin-top: 30px; padding-bottom: 15px; margin-bottom: 20px; border-bottom: 2px solid #dee2e6;\">"
           "<h3 style=\"margin: 0; color: #212529; font-size: 1.25rem; font-weight: 600;\">Sensor Measurement Settings</h3>"
           "</div>"
           "<form id=\"configForm\">"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Distance Mode</label>"
           "<select class=\"form-control\" id=\"distance_mode\" name=\"distance_mode\">"
           "<option value=\"1\">SHORT (<1.3m)</option>"
           "<option value=\"2\">LONG (<4m)</option>"
           "</select>"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Timing Budget (ms)</label>"
           "<select class=\"form-control\" id=\"timing_budget_ms\" name=\"timing_budget_ms\">"
           "<option value=\"15\">15</option>"
           "<option value=\"20\">20</option>"
           "<option value=\"33\">33</option>"
           "<option value=\"50\">50</option>"
           "<option value=\"100\">100</option>"
           "<option value=\"200\">200</option>"
           "<option value=\"500\">500</option>"
           "</select>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"form-group\">"
           "<label>Inter-Measurement Period (ms)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"inter_measurement_ms\" name=\"inter_measurement_ms\" min=\"15\" step=\"1\">"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>ROI X Size</label>"
           "<input type=\"number\" class=\"form-control\" id=\"roi_x_size\" name=\"roi_x_size\" min=\"4\" max=\"16\" value=\"16\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>ROI Y Size</label>"
           "<input type=\"number\" class=\"form-control\" id=\"roi_y_size\" name=\"roi_y_size\" min=\"4\" max=\"16\" value=\"16\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>ROI Center SPAD</label>"
           "<input type=\"number\" class=\"form-control\" id=\"roi_center_spad\" name=\"roi_center_spad\" min=\"0\" max=\"199\" value=\"199\">"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Offset (mm)</label>"
           "<div class=\"input-group\">"
           "<input type=\"number\" class=\"form-control\" id=\"offset_mm\" name=\"offset_mm\" min=\"-128\" max=\"127\" value=\"0\">"
           "<button type=\"button\" class=\"btn btn-secondary\" onclick=\"calibrateOffset()\">Calibrate</button>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Xtalk (cps)</label>"
           "<div class=\"input-group\">"
           "<input type=\"number\" class=\"form-control\" id=\"xtalk_cps\" name=\"xtalk_cps\" min=\"0\" max=\"65535\" value=\"0\">"
           "<button type=\"button\" class=\"btn btn-secondary\" onclick=\"calibrateXtalk()\">Calibrate</button>"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Signal Threshold (kcps)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"signal_threshold_kcps\" name=\"signal_threshold_kcps\" min=\"0\" max=\"65535\" value=\"1024\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Sigma Threshold (mm)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"sigma_threshold_mm\" name=\"sigma_threshold_mm\" min=\"0\" max=\"65535\" value=\"15\">"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>Threshold Low (mm)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"threshold_low_mm\" name=\"threshold_low_mm\" min=\"0\" max=\"4000\" value=\"0\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>Threshold High (mm)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"threshold_high_mm\" name=\"threshold_high_mm\" min=\"0\" max=\"4000\" value=\"0\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>Threshold Window</label>"
           "<select class=\"form-control\" id=\"threshold_window\" name=\"threshold_window\">"
           "<option value=\"0\">Below</option>"
           "<option value=\"1\">Above</option>"
           "<option value=\"2\">Out</option>"
           "<option value=\"3\">In</option>"
           "</select>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Interrupt Polarity</label>"
           "<select class=\"form-control\" id=\"interrupt_polarity\" name=\"interrupt_polarity\">"
           "<option value=\"0\">Active Low</option>"
           "<option value=\"1\">Active High</option>"
           "</select>"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>I2C Address</label>"
           "<input type=\"text\" class=\"form-control\" id=\"i2c_address\" name=\"i2c_address\" pattern=\"0x[0-9A-Fa-f]{2}\" value=\"0x29\">"
           "</div>"
           "</div>"
           "</div>"
           "<div style=\"margin-top: 30px; padding-top: 20px; border-top: 1px solid #dee2e6;\">"
           "<div style=\"display: flex; justify-content: space-between; gap: 15px;\">"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveConfig()\" style=\"flex: 1;\">Save Measurement Settings</button>"
           "<button type=\"button\" class=\"btn btn-secondary\" onclick=\"loadConfig()\" style=\"flex: 1;\">Load Current Settings</button>"
           "<button type=\"button\" class=\"btn btn-warning\" onclick=\"resetConfig()\" style=\"flex: 1;\">Reset to Defaults</button>"
           "</div>"
           "</div>"
           "</form>"
           "</div>"
           "<div id=\"message\" class=\"alert\" style=\"display:none; margin-top:20px;\"></div>"
           "</form>"
           "</div>"
           "</div>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message');"
           "  msg.textContent = text;"
           "  msg.className = 'alert alert-' + type;"
           "  msg.style.display = 'block';"
           "  setTimeout(() => msg.style.display = 'none', 5000);"
           "}"
           "function loadIpConfig() {"
           "  fetch('/api/ipconfig')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      var dhcpCheckbox = document.getElementById('use_dhcp');"
           "      var staticFields = document.getElementById('staticIpFields');"
           "      var dnsFields = document.getElementById('dnsFields');"
           "      if (dhcpCheckbox && data.use_dhcp !== undefined) dhcpCheckbox.checked = data.use_dhcp;"
           "      if (staticFields && data.use_dhcp !== undefined) staticFields.style.display = data.use_dhcp ? 'none' : 'block';"
           "      if (dnsFields && data.use_dhcp !== undefined) dnsFields.style.display = data.use_dhcp ? 'none' : 'block';"
           "      var ipAddr = document.getElementById('ip_address');"
           "      var netmask = document.getElementById('netmask');"
           "      var gateway = document.getElementById('gateway');"
           "      var dns1 = document.getElementById('dns1');"
           "      var dns2 = document.getElementById('dns2');"
           "      if (ipAddr) ipAddr.value = (data.ip_address && data.ip_address !== '0.0.0.0') ? data.ip_address : '';"
           "      if (netmask) netmask.value = (data.netmask && data.netmask !== '0.0.0.0') ? data.netmask : '';"
           "      if (gateway) gateway.value = (data.gateway && data.gateway !== '0.0.0.0') ? data.gateway : '';"
           "      if (dns1) dns1.value = (data.dns1 && data.dns1 !== '0.0.0.0') ? data.dns1 : '';"
           "      if (dns2) dns2.value = (data.dns2 && data.dns2 !== '0.0.0.0') ? data.dns2 : '';"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load IP configuration:', err);"
           "    });"
           "}"
           "function saveIpConfig() {"
           "  const data = {"
           "    use_dhcp: document.getElementById('use_dhcp').checked,"
           "    ip_address: document.getElementById('ip_address').value,"
           "    netmask: document.getElementById('netmask').value,"
           "    gateway: document.getElementById('gateway').value,"
           "    dns1: document.getElementById('dns1').value,"
           "    dns2: document.getElementById('dns2').value"
           "  };"
           "  fetch('/api/ipconfig', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify(data)"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage(data.message, 'success');"
           "      } else {"
           "        showMessage('Failed to save IP configuration', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to save IP configuration:', err);"
           "      showMessage('Failed to save IP configuration', 'danger');"
           "    });"
           "}"
           "function loadModbusConfig() {"
           "  fetch('/api/modbus')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.enabled !== undefined) document.getElementById('modbus_enabled').checked = data.enabled;"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load Modbus configuration:', err);"
           "    });"
           "}"
           "function saveModbusConfig() {"
           "  const data = {"
           "    enabled: document.getElementById('modbus_enabled').checked"
           "  };"
           "  fetch('/api/modbus', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify(data)"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage(data.message, 'success');"
           "      } else {"
           "        showMessage('Failed to save Modbus configuration', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to save Modbus configuration:', err);"
           "      showMessage('Failed to save Modbus configuration', 'danger');"
           "    });"
           "}"
           "function loadSensorConfig() {"
           "  Promise.all(["
           "    fetch('/api/sensor/enabled').then(r => r.json()),"
           "    fetch('/api/sensor/byteoffset').then(r => r.json())"
           "  ])"
           "    .then(([enabledData, byteOffsetData]) => {"
           "      const sensorEnabled = document.getElementById('sensor_enabled');"
           "      const sensorFields = document.getElementById('sensorSettingsFields');"
           "      const byteRangeSelect = document.getElementById('sensor_byte_range');"
           "      if (sensorEnabled && enabledData.enabled !== undefined) {"
           "        sensorEnabled.checked = enabledData.enabled;"
           "        if (sensorFields) {"
           "          sensorFields.style.display = enabledData.enabled ? 'block' : 'none';"
           "        }"
           "      }"
           "      if (byteRangeSelect && byteOffsetData.start_byte !== undefined) {"
           "        byteRangeSelect.value = byteOffsetData.start_byte.toString();"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load sensor configuration:', err);"
           "    });"
           "}"
           "function saveSensorConfig() {"
           "  const enabled = document.getElementById('sensor_enabled').checked;"
           "  const byteRangeSelect = document.getElementById('sensor_byte_range');"
           "  const startByte = byteRangeSelect ? parseInt(byteRangeSelect.value) : 0;"
           "  Promise.all(["
           "    fetch('/api/sensor/enabled', {"
           "      method: 'POST',"
           "      headers: { 'Content-Type': 'application/json' },"
           "      body: JSON.stringify({ enabled: enabled })"
           "    }).then(r => r.json()),"
           "    fetch('/api/sensor/byteoffset', {"
           "      method: 'POST',"
           "      headers: { 'Content-Type': 'application/json' },"
           "      body: JSON.stringify({ start_byte: startByte })"
           "    }).then(r => r.json())"
           "  ])"
           "    .then(([enabledResult, byteOffsetResult]) => {"
           "      if (enabledResult.status === 'ok' && byteOffsetResult.status === 'ok') {"
           "        showMessage('Sensor configuration saved successfully', 'success');"
           "        const sensorFields = document.getElementById('sensorSettingsFields');"
           "        if (sensorFields) {"
           "          sensorFields.style.display = enabled ? 'block' : 'none';"
           "        }"
           "        updateNavigationBar();"
           "      } else {"
           "        showMessage('Failed to save sensor configuration', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to save sensor configuration:', err);"
           "      showMessage('Failed to save sensor configuration', 'danger');"
           "    });"
           "}"
           "function updateNavigationBar() {"
           "  fetch('/api/sensor/enabled')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const navItems = document.querySelectorAll('nav li.sensor-nav-item');"
           "      navItems.forEach(item => {"
           "        if (item) {"
           "          item.style.display = data.enabled ? 'block' : 'none';"
           "        }"
           "      });"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to update navigation bar:', err);"
           "    });"
           "}"
           "function loadConfig() {" 
           "  fetch('/api/config')" 
           "    .then(r => {" 
           "      if (!r.ok) throw new Error('HTTP ' + r.status);" 
           "      return r.json();" 
           "    })" 
           "    .then(data => {" 
           "      if (data.distance_mode !== undefined && data.distance_mode !== null) document.getElementById('distance_mode').value = data.distance_mode;" 
           "      if (data.timing_budget_ms !== undefined && data.timing_budget_ms !== null) document.getElementById('timing_budget_ms').value = data.timing_budget_ms;" 
           "      if (data.inter_measurement_ms !== undefined && data.inter_measurement_ms !== null) document.getElementById('inter_measurement_ms').value = data.inter_measurement_ms;" 
           "      if (data.roi_x_size !== undefined && data.roi_x_size !== null) document.getElementById('roi_x_size').value = data.roi_x_size;" 
           "      if (data.roi_y_size !== undefined && data.roi_y_size !== null) document.getElementById('roi_y_size').value = data.roi_y_size;" 
           "      if (data.roi_center_spad !== undefined && data.roi_center_spad !== null) document.getElementById('roi_center_spad').value = data.roi_center_spad;" 
           "      if (data.offset_mm !== undefined && data.offset_mm !== null) document.getElementById('offset_mm').value = data.offset_mm;" 
           "      if (data.xtalk_cps !== undefined && data.xtalk_cps !== null) document.getElementById('xtalk_cps').value = data.xtalk_cps;" 
           "      if (data.signal_threshold_kcps !== undefined && data.signal_threshold_kcps !== null) document.getElementById('signal_threshold_kcps').value = data.signal_threshold_kcps;" 
           "      if (data.sigma_threshold_mm !== undefined && data.sigma_threshold_mm !== null) document.getElementById('sigma_threshold_mm').value = data.sigma_threshold_mm;" 
           "      if (data.threshold_low_mm !== undefined && data.threshold_low_mm !== null) document.getElementById('threshold_low_mm').value = data.threshold_low_mm;" 
           "      if (data.threshold_high_mm !== undefined && data.threshold_high_mm !== null) document.getElementById('threshold_high_mm').value = data.threshold_high_mm;" 
           "      if (data.threshold_window !== undefined && data.threshold_window !== null) document.getElementById('threshold_window').value = data.threshold_window;" 
           "      if (data.interrupt_polarity !== undefined && data.interrupt_polarity !== null) document.getElementById('interrupt_polarity').value = data.interrupt_polarity;" 
           "      if (data.i2c_address !== undefined && data.i2c_address !== null) document.getElementById('i2c_address').value = '0x' + data.i2c_address.toString(16).padStart(2, '0');" 
           "      showMessage('Configuration loaded', 'success');" 
           "    })" 
           "    .catch(err => {" 
           "      console.error('Failed to load configuration:', err);" 
           "      showMessage('Failed to load configuration', 'danger');" 
           "    });" 
           "}"
           "function saveConfig() {"
           "  const addr = document.getElementById('i2c_address').value;"
           "  const addrNum = parseInt(addr, 16);"
           "  const data = {"
           "    distance_mode: parseInt(document.getElementById('distance_mode').value),"
           "    timing_budget_ms: parseInt(document.getElementById('timing_budget_ms').value),"
           "    inter_measurement_ms: parseInt(document.getElementById('inter_measurement_ms').value),"
           "    roi_x_size: parseInt(document.getElementById('roi_x_size').value),"
           "    roi_y_size: parseInt(document.getElementById('roi_y_size').value),"
           "    roi_center_spad: parseInt(document.getElementById('roi_center_spad').value),"
           "    offset_mm: parseInt(document.getElementById('offset_mm').value),"
           "    xtalk_cps: parseInt(document.getElementById('xtalk_cps').value),"
           "    signal_threshold_kcps: parseInt(document.getElementById('signal_threshold_kcps').value),"
           "    sigma_threshold_mm: parseInt(document.getElementById('sigma_threshold_mm').value),"
           "    threshold_low_mm: parseInt(document.getElementById('threshold_low_mm').value),"
           "    threshold_high_mm: parseInt(document.getElementById('threshold_high_mm').value),"
           "    threshold_window: parseInt(document.getElementById('threshold_window').value),"
           "    interrupt_polarity: parseInt(document.getElementById('interrupt_polarity').value),"
           "    i2c_address: addrNum"
           "  };"
           "  fetch('/api/config', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify(data)"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage('Configuration saved successfully', 'success');"
           "      } else {"
           "        showMessage('Failed to save configuration', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to save configuration:', err);"
           "      showMessage('Failed to save configuration', 'danger');"
           "    });"
           "}"
           "function resetConfig() {"
           "  if (confirm('Reset to default configuration?')) {"
           "    document.getElementById('distance_mode').value = 2;"
           "    document.getElementById('timing_budget_ms').value = 100;"
           "    document.getElementById('inter_measurement_ms').value = 100;"
           "    document.getElementById('roi_x_size').value = 16;"
           "    document.getElementById('roi_y_size').value = 16;"
           "    document.getElementById('roi_center_spad').value = 199;"
           "    document.getElementById('offset_mm').value = 0;"
           "    document.getElementById('xtalk_cps').value = 0;"
           "    document.getElementById('signal_threshold_kcps').value = 1024;"
           "    document.getElementById('sigma_threshold_mm').value = 15;"
           "    document.getElementById('threshold_low_mm').value = 0;"
           "    document.getElementById('threshold_high_mm').value = 0;"
           "    document.getElementById('threshold_window').value = 0;"
           "    document.getElementById('interrupt_polarity').value = 1;"
           "    document.getElementById('i2c_address').value = '0x29';"
           "    showMessage('Form reset to defaults', 'info');"
           "  }"
           "}"
           "function calibrateOffset() {"
           "  const dist = prompt('Enter target distance in mm (recommended: 100mm):', '100');"
           "  if (dist) {"
           "    fetch('/api/calibrate/offset', {"
           "      method: 'POST',"
           "      headers: { 'Content-Type': 'application/json' },"
           "      body: JSON.stringify({ target_distance_mm: parseInt(dist) })"
           "    })"
           "      .then(r => {"
           "        if (!r.ok) throw new Error('HTTP ' + r.status);"
           "        return r.json();"
           "      })"
           "      .then(data => {"
           "        if (data.status === 'ok') {"
           "          document.getElementById('offset_mm').value = data.offset_mm;"
           "          showMessage('Offset calibration successful: ' + data.offset_mm + ' mm', 'success');"
           "        } else {"
           "          showMessage('Offset calibration failed', 'danger');"
           "        }"
           "      })"
           "      .catch(err => {"
           "        console.error('Offset calibration error:', err);"
           "        showMessage('Offset calibration failed', 'danger');"
           "      });"
           "  }"
           "}"
           "function calibrateXtalk() {"
           "  const dist = prompt('Enter target distance in mm (recommended: 600mm):', '600');"
           "  if (dist) {"
           "    fetch('/api/calibrate/xtalk', {"
           "      method: 'POST',"
           "      headers: { 'Content-Type': 'application/json' },"
           "      body: JSON.stringify({ target_distance_mm: parseInt(dist) })"
           "    })"
           "      .then(r => {"
           "        if (!r.ok) throw new Error('HTTP ' + r.status);"
           "        return r.json();"
           "      })"
           "      .then(data => {"
           "        if (data.status === 'ok') {"
           "          document.getElementById('xtalk_cps').value = data.xtalk_cps;"
           "          showMessage('Xtalk calibration successful: ' + data.xtalk_cps + ' cps', 'success');"
           "        } else {"
           "          showMessage('Xtalk calibration failed', 'danger');"
           "        }"
           "      })"
           "      .catch(err => {"
           "        console.error('Xtalk calibration error:', err);"
           "        showMessage('Xtalk calibration failed', 'danger');"
           "      });"
           "  }"
           "}"
           "window.onload = function() {" 
           "  console.log('Page loaded, initializing configuration...');" 
           "  try {" 
           "    loadConfig();" 
           "    loadIpConfig();" 
           "    loadModbusConfig();"
           "    loadSensorConfig();"
           "    updateNavigationBar();"
           "    const sensorEnabled = document.getElementById('sensor_enabled');"
           "    if (sensorEnabled) {"
           "      sensorEnabled.addEventListener('change', function() {"
           "        const sensorFields = document.getElementById('sensorSettingsFields');"
           "        if (sensorFields) {"
           "          sensorFields.style.display = this.checked ? 'block' : 'none';"
           "        }"
           "      });"
           "    }" 
           "    var dhcpCheckbox = document.getElementById('use_dhcp');" 
           "    if (dhcpCheckbox) {" 
           "      dhcpCheckbox.addEventListener('change', function() {" 
           "        const useDhcp = this.checked;" 
           "        const staticFields = document.getElementById('staticIpFields');" 
           "        const dnsFields = document.getElementById('dnsFields');" 
           "        if (staticFields) {" 
           "          staticFields.style.display = useDhcp ? 'none' : 'block';" 
           "        }" 
           "        if (dnsFields) {" 
           "          dnsFields.style.display = useDhcp ? 'none' : 'block';" 
           "        }" 
           "        if (!useDhcp) {" 
           "          fetch('/api/ipconfig')" 
           "            .then(r => {" 
           "              if (!r.ok) throw new Error('HTTP ' + r.status);" 
           "              return r.json();" 
           "            })" 
           "            .then(data => {" 
           "              var ipAddr = document.getElementById('ip_address');" 
           "              var netmask = document.getElementById('netmask');" 
           "              var gateway = document.getElementById('gateway');" 
           "              var dns1 = document.getElementById('dns1');" 
           "              var dns2 = document.getElementById('dns2');" 
           "              if (ipAddr) ipAddr.value = (data.ip_address && data.ip_address !== '0.0.0.0') ? data.ip_address : '';" 
           "              if (netmask) netmask.value = (data.netmask && data.netmask !== '0.0.0.0') ? data.netmask : '';" 
           "              if (gateway) gateway.value = (data.gateway && data.gateway !== '0.0.0.0') ? data.gateway : '';" 
           "              if (dns1) dns1.value = (data.dns1 && data.dns1 !== '0.0.0.0') ? data.dns1 : '';" 
           "              if (dns2) dns2.value = (data.dns2 && data.dns2 !== '0.0.0.0') ? data.dns2 : '';" 
           "            })" 
           "            .catch(err => {" 
           "              console.error('Failed to reload IP configuration:', err);" 
           "            });" 
           "        }" 
           "      });" 
           "    } else {" 
           "      console.error('DHCP checkbox not found');" 
           "    }" 
           "  } catch (err) {" 
           "    console.error('Error initializing page:', err);" 
           "  }" 
           "};"
           "</script>"
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</body>"
           "</html>";
}

const char *webui_get_status_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>VL53L1x Status</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".navbar-nav li.sensor-nav-item { display: none; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".row { display: flex; flex-wrap: wrap; margin: 0 -10px; }"
           ".col-md-6 { flex: 0 0 50%; max-width: 50%; padding: 0 10px; }"
           "@media (max-width: 768px) { .col-md-6 { flex: 0 0 100%; max-width: 100%; } }"
           ".status-card { border: 1px solid #ddd; border-radius: 8px; padding: 0; margin-bottom: 20px; background-color: #fff; overflow: hidden; }"
           ".card-header { background-color: #f8f9fa; padding: 15px 20px; border-bottom: 1px solid #dee2e6; margin: 0; }"
           ".card-header h2, .card-header h3 { margin: 0; color: #212529; font-size: 1.25rem; font-weight: 600; }"
           ".card-body { padding: 20px; }"
           ".status-value { font-size: 24px; font-weight: bold; color: #007bff; }"
           ".distance-bar-container { margin-top: 20px; }"
           ".distance-bar-wrapper { position: relative; width: 100%; height: 40px; background-color: #e9ecef; border-radius: 4px; overflow: hidden; border: 1px solid #ced4da; }"
           ".distance-bar-fill { height: 100%; transition: width 0.3s ease, background-color 0.3s ease; border-radius: 4px; }"
           ".distance-bar-label { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); font-weight: bold; color: #333; text-shadow: 0 0 3px rgba(255,255,255,0.8); pointer-events: none; z-index: 10; }"
           ".distance-bar-scale { display: flex; justify-content: space-between; margin-top: 5px; font-size: 11px; color: #666; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\">Configuration</a></li>"
           "<li><a href=\"/vl53l1x\" class=\"active\">VL53L1x</a></li>"
           "<li><a href=\"/inputassembly\">T->O</a></li>"
           "<li><a href=\"/outputassembly\">O->T</a></li>"
           "<li><a href=\"/ota\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>VL53L1x Sensor Status</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div style=\"margin-bottom: 20px; padding: 12px; background-color: #f8f9fa; border-left: 4px solid #007bff; border-radius: 4px;\">"
           "<p style=\"margin: 0; color: #495057; font-size: 14px; line-height: 1.6;\">"
           "<strong>Real-Time Sensor Data:</strong> This page displays live distance measurements and sensor status from the VL53L1x time-of-flight sensor. "
           "Data updates automatically every 250ms. The distance range bar provides a visual representation of the current measurement relative to the configured maximum range. "
           "Status codes indicate measurement validity, with detailed error descriptions when issues are detected."
           "</p>"
           "</div>"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h3>Current Readings</h3>"
           "</div>"
           "<div class=\"card-body\">"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<p><strong>Distance:</strong> <span class=\"status-value\" id=\"distance\">-</span> mm</p>"
           "<p><strong>Status:</strong> <span id=\"status\">-</span></p>"
           "<p><strong>Ambient:</strong> <span id=\"ambient\">-</span> kcps</p>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<p><strong>Signal per SPAD:</strong> <span id=\"sig_per_spad\">-</span> kcps/SPAD</p>"
           "<p><strong>Number of SPADs:</strong> <span id=\"num_spads\">-</span></p>"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h3>Distance Range</h3>"
           "</div>"
           "<div class=\"card-body\">"
           "<div class=\"distance-bar-container\">"
           "<div class=\"distance-bar-wrapper\">"
           "<div class=\"distance-bar-fill\" id=\"distanceBarFill\" style=\"width: 0%; background-color: #dc3545;\"></div>"
           "<div class=\"distance-bar-label\" id=\"distanceBarLabel\">- mm</div>"
           "</div>"
           "<div class=\"distance-bar-scale\">"
           "<span id=\"scaleMin\">0</span>"
           "<span id=\"scaleMax\">4000</span>"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</div>"
           "<script>"
           "let currentDistanceMode = 2;"
           "let maxDistance = 4000;"
           ""
           "function getStatusDescription(statusCode) {"
           "  const statusMap = {"
           "    0: 'Valid measurement',"
           "    1: 'Sigma failed (measurement uncertainty too high)',"
           "    2: 'Signal failed (signal too weak)',"
           "    3: 'Target out of range',"
           "    4: 'Out of bounds (signal failed)',"
           "    5: 'Range valid but wrapped',"
           "    6: 'Target out of range',"
           "    7: 'Wrap-around (target beyond max range)',"
           "    9: 'Range valid but wrapped',"
           "    10: 'Target out of range',"
           "    11: 'Range valid but wrapped',"
           "    12: 'Range valid but wrapped',"
           "    13: 'Range valid but wrapped',"
           "    255: 'Invalid/unknown status'"
           "  };"
           "  return statusMap[statusCode] || 'Unknown status code';"
           "}"
           ""
           "function lerp(start, end, t) {"
           "  return start + (end - start) * t;"
           "}"
           ""
           "function getGradientColor(value, max) {"
           "  if (value <= 0) return 'rgb(220, 53, 69)';"
           "  if (value >= max) return 'rgb(40, 167, 69)';"
           "  const ratio = value / max;"
           "  let r, g, b;"
           "  if (ratio < 0.5) {"
           "    const t = ratio * 2;"
           "    r = Math.round(lerp(220, 255, t));"
           "    g = Math.round(lerp(53, 193, t));"
           "    b = Math.round(lerp(69, 7, t));"
           "  } else {"
           "    const t = (ratio - 0.5) * 2;"
           "    r = Math.round(lerp(255, 40, t));"
           "    g = Math.round(lerp(193, 167, t));"
           "    b = Math.round(lerp(7, 69, t));"
           "  }"
           "  return 'rgb(' + r + ',' + g + ',' + b + ')';"
           "}"
           ""
           "function updateDistanceBar(distance, distanceMode) {"
           "  const maxDist = distanceMode === 1 ? 1300 : 4000;"
           "  maxDistance = maxDist;"
           "  currentDistanceMode = distanceMode;"
           "  "
           "  document.getElementById('scaleMax').textContent = maxDist;"
           "  "
           "  if (distance === undefined || distance === null || distance < 0) {"
           "    document.getElementById('distanceBarFill').style.width = '0%';"
           "    document.getElementById('distanceBarFill').style.backgroundColor = '#dc3545';"
           "    document.getElementById('distanceBarLabel').textContent = '- mm';"
           "    return;"
           "  }"
           "  "
           "  const percentage = Math.min(100, (distance / maxDist) * 100);"
           "  const clampedDistance = Math.min(distance, maxDist);"
           "  "
           "  document.getElementById('distanceBarFill').style.width = percentage + '%';"
           "  document.getElementById('distanceBarFill').style.backgroundColor = getGradientColor(clampedDistance, maxDist);"
           "  document.getElementById('distanceBarLabel').textContent = distance + ' mm';"
           "}"
           ""
           "function updateStatus() {"
           "  fetch('/api/status')"
           "    .then(r => {"
           "      if (!r.ok) {"
           "        throw new Error('HTTP ' + r.status);"
           "      }"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      console.log('API data received:', data);"
           "      if (data.distance_mm !== undefined && data.distance_mm !== null) {"
           "        document.getElementById('distance').textContent = data.distance_mm;"
           "      } else {"
           "        document.getElementById('distance').textContent = '-';"
           "      }"
           "      if (data.status !== undefined && data.status !== null) {"
           "        if (data.status === 0) {"
           "          document.getElementById('status').textContent = 'Valid';"
           "        } else {"
           "          const description = getStatusDescription(data.status);"
           "          document.getElementById('status').textContent = 'Error (' + data.status + ') ' + description;"
           "        }"
           "      } else {"
           "        document.getElementById('status').textContent = '-';"
           "      }"
           "      if (data.ambient_kcps !== undefined && data.ambient_kcps !== null) {"
           "        document.getElementById('ambient').textContent = data.ambient_kcps;"
           "      } else {"
           "        document.getElementById('ambient').textContent = '-';"
           "      }"
           "      if (data.sig_per_spad_kcps !== undefined && data.sig_per_spad_kcps !== null) {"
           "        document.getElementById('sig_per_spad').textContent = data.sig_per_spad_kcps;"
           "      } else {"
           "        document.getElementById('sig_per_spad').textContent = '-';"
           "      }"
           "      if (data.num_spads !== undefined && data.num_spads !== null) {"
           "        document.getElementById('num_spads').textContent = data.num_spads;"
           "      } else {"
           "        document.getElementById('num_spads').textContent = '-';"
           "      }"
           "      "
           "      const distanceMode = data.distance_mode !== undefined ? data.distance_mode : 2;"
           "      updateDistanceBar(data.distance_mm, distanceMode);"
           "    })"
           "    .catch(err => {"
           "      console.error('Status update error:', err);"
           "    });"
           "}"
           "function updateNavigationBar() {"
           "  fetch('/api/sensor/enabled')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const navItems = document.querySelectorAll('nav li.sensor-nav-item');"
           "      navItems.forEach(item => {"
           "        if (item) {"
           "          item.style.display = data.enabled ? 'block' : 'none';"
           "        }"
           "      });"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to update navigation bar:', err);"
           "    });"
           "}"
           "function initPage() {"
           "  updateStatus();"
           "  setInterval(updateStatus, 250);"
           "  updateNavigationBar();"
           "}"
           "if (document.readyState === 'loading') {"
           "  document.addEventListener('DOMContentLoaded', initPage);"
           "} else {"
           "  initPage();"
           "}"
           "</script>"
           "</body>"
           "</html>";
}

const char *webui_get_ethernetip_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>EtherNet/IP Status</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".navbar-nav li.sensor-nav-item { display: none; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".status-card { border: 1px solid #ddd; border-radius: 8px; padding: 0; margin-bottom: 20px; background-color: #fff; overflow: hidden; }"
           ".card-header { background-color: #f8f9fa; padding: 15px 20px; border-bottom: 1px solid #dee2e6; margin: 0; }"
           ".card-header h2, .card-header h3 { margin: 0; color: #212529; font-size: 1.25rem; font-weight: 600; }"
           ".card-body { padding: 20px; }"
           ".status-value { font-size: 24px; font-weight: bold; color: #007bff; }"
           ".bytes-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }"
           ".byte-row { margin-bottom: 10px; padding: 10px; background-color: #f8f9fa; border-radius: 4px; }"
           ".byte-label { font-weight: 600; color: #495057; margin-bottom: 8px; font-size: 14px; }"
           ".bit-checkbox { width: 18px; height: 18px; margin: 0 2px; cursor: not-allowed; pointer-events: none; vertical-align: middle; appearance: none; -webkit-appearance: none; -moz-appearance: none; border: 1px solid #adb5bd; border-radius: 3px; position: relative; }"
           ".bit-checkbox:checked { background-color: #007bff !important; border-color: #007bff !important; }"
           ".bit-checkbox:checked::after { content: '✓'; color: #fff; font-size: 12px; font-weight: bold; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); line-height: 1; }"
           ".bit-checkbox:not(:checked) { background-color: #e9ecef !important; border-color: #adb5bd !important; }"
           ".bit-checkbox[disabled] { opacity: 1; }"
           ".bit-label { font-size: 11px; color: #6c757d; margin: 0 2px; }"
           ".bits-container { display: flex; align-items: center; flex-wrap: wrap; }"
           "@media (max-width: 768px) { .bytes-grid { grid-template-columns: 1fr; } }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\">Configuration</a></li>"
           "<li class=\"sensor-nav-item\"><a href=\"/vl53l1x\">VL53L1x</a></li>"
           "<li><a href=\"/inputassembly\">T->O</a></li>"
           "<li><a href=\"/outputassembly\" class=\"active\">O->T</a></li>"
           "<li><a href=\"/ota\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>EtherNet/IP Output Assembly</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div style=\"margin-bottom: 20px; padding: 12px; background-color: #f8f9fa; border-left: 4px solid #007bff; border-radius: 4px;\">"
           "<p style=\"margin: 0; color: #495057; font-size: 14px; line-height: 1.6;\">"
           "<strong>Output Assembly 150:</strong> This page displays the current state of the EtherNet/IP Output Assembly (O->T, Output to Target). "
           "This 32-byte assembly contains data sent from the EtherNet/IP scanner to the device. Each byte is displayed in both hexadecimal and decimal format, "
           "with individual bits shown as checkboxes. Blue checkboxes indicate active (set) bits, while gray checkboxes indicate inactive (cleared) bits. "
           "Data updates automatically every 250ms."
           "</p>"
           "</div>"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h3>Output Assembly 150</h3>"
           "</div>"
           "<div class=\"card-body\">"
           "<p><strong>Assembly Size:</strong> 32 bytes | <strong>Status:</strong> <span id=\"output_status\">Active</span></p>"
           "<div class=\"bytes-grid\" id=\"bytes_container\"></div>"
           "</div>"
           "</div>"
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</div>"
           "<script>"
           "function createByteRow(byteIndex, byteValue) {"
           "  const row = document.createElement('div');"
           "  row.className = 'byte-row';"
           "  const hexValue = '0x' + byteValue.toString(16).padStart(2, '0').toUpperCase();"
           "  const decValue = byteValue.toString().padStart(3, '0');"
           "  row.innerHTML = '<div class=\"byte-label\">Byte ' + byteIndex + ' HEX (' + hexValue + ') | DEC ' + decValue + '</div>';"
           "  "
           "  const bitsContainer = document.createElement('div');"
           "  bitsContainer.className = 'bits-container';"
           "  "
           "  for (let bit = 0; bit <= 7; bit++) {"
           "    const bitValue = (byteValue >> bit) & 1;"
           "    const checkbox = document.createElement('input');"
           "    checkbox.type = 'checkbox';"
           "    checkbox.className = 'bit-checkbox';"
           "    checkbox.id = 'byte' + byteIndex + '_bit' + bit;"
           "    checkbox.checked = bitValue === 1;"
           "    checkbox.disabled = true;"
           "    "
           "    const label = document.createElement('span');"
           "    label.className = 'bit-label';"
           "    label.textContent = bit;"
           "    "
           "    bitsContainer.appendChild(checkbox);"
           "    bitsContainer.appendChild(label);"
           "  }"
           "  "
           "  row.appendChild(bitsContainer);"
           "  return row;"
           "}"
           ""
           "function updateStatus() {"
           "  fetch('/api/status')"
           "    .then(r => {"
           "      if (!r.ok) {"
           "        throw new Error('HTTP ' + r.status);"
           "      }"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.output_assembly_150 && data.output_assembly_150.raw_bytes) {"
           "        const container = document.getElementById('bytes_container');"
           "        if (container) {"
           "          container.innerHTML = '';"
           "          for (let i = 0; i < data.output_assembly_150.raw_bytes.length; i++) {"
           "            const byteValue = data.output_assembly_150.raw_bytes[i];"
           "            const row = createByteRow(i, byteValue);"
           "            container.appendChild(row);"
           "          }"
           "        }"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Status update error:', err);"
           "    });"
           "}"
           "updateStatus();"
           "function updateNavigationBar() {"
           "  fetch('/api/sensor/enabled')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const navItems = document.querySelectorAll('nav li.sensor-nav-item');"
           "      navItems.forEach(item => {"
           "        if (item) {"
           "          item.style.display = data.enabled ? 'block' : 'none';"
           "        }"
           "      });"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to update navigation bar:', err);"
           "    });"
           "}"
           "updateNavigationBar();"
           "setInterval(updateStatus, 250);"
           "</script>"
           "</body>"
           "</html>";
}

const char *webui_get_input_assembly_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>Input Assembly Status</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".navbar-nav li.sensor-nav-item { display: none; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".status-card { border: 1px solid #ddd; border-radius: 8px; padding: 0; margin-bottom: 20px; background-color: #fff; overflow: hidden; }"
           ".card-header { background-color: #f8f9fa; padding: 15px 20px; border-bottom: 1px solid #dee2e6; margin: 0; }"
           ".card-header h2, .card-header h3 { margin: 0; color: #212529; font-size: 1.25rem; font-weight: 600; }"
           ".card-body { padding: 20px; }"
           ".status-value { font-size: 24px; font-weight: bold; color: #007bff; }"
           ".bytes-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }"
           ".byte-row { margin-bottom: 10px; padding: 10px; background-color: #f8f9fa; border-radius: 4px; }"
           ".byte-label { font-weight: 600; color: #495057; margin-bottom: 8px; font-size: 14px; }"
           ".bit-checkbox { width: 18px; height: 18px; margin: 0 2px; cursor: not-allowed; pointer-events: none; vertical-align: middle; appearance: none; -webkit-appearance: none; -moz-appearance: none; border: 1px solid #adb5bd; border-radius: 3px; position: relative; }"
           ".bit-checkbox:checked { background-color: #007bff !important; border-color: #007bff !important; }"
           ".bit-checkbox:checked::after { content: '✓'; color: #fff; font-size: 12px; font-weight: bold; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); line-height: 1; }"
           ".bit-checkbox:not(:checked) { background-color: #e9ecef !important; border-color: #adb5bd !important; }"
           ".bit-checkbox[disabled] { opacity: 1; }"
           ".bit-label { font-size: 11px; color: #6c757d; margin: 0 2px; }"
           ".bits-container { display: flex; align-items: center; flex-wrap: wrap; }"
           "@media (max-width: 768px) { .bytes-grid { grid-template-columns: 1fr; } }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\">Configuration</a></li>"
           "<li class=\"sensor-nav-item\"><a href=\"/vl53l1x\">VL53L1x</a></li>"
           "<li><a href=\"/inputassembly\" class=\"active\">T->O</a></li>"
           "<li><a href=\"/outputassembly\">O->T</a></li>"
           "<li><a href=\"/ota\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>EtherNet/IP Input Assembly</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div style=\"margin-bottom: 20px; padding: 12px; background-color: #f8f9fa; border-left: 4px solid #007bff; border-radius: 4px;\">"
           "<p style=\"margin: 0; color: #495057; font-size: 14px; line-height: 1.6;\">"
           "<strong>Input Assembly 100:</strong> This page displays the current state of the EtherNet/IP Input Assembly (T->O, Target to Output). "
           "This 32-byte assembly contains data sent from the device to the EtherNet/IP scanner. Each byte is displayed in both hexadecimal and decimal format, "
           "with individual bits shown as checkboxes. Blue checkboxes indicate active (set) bits, while gray checkboxes indicate inactive (cleared) bits. "
           "Data updates automatically every 250ms."
           "</p>"
           "</div>"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h3>Input Assembly 100</h3>"
           "</div>"
           "<div class=\"card-body\">"
           "<p><strong>Assembly Size:</strong> 32 bytes | <strong>Status:</strong> <span id=\"input_status\">Active</span></p>"
           "<div class=\"bytes-grid\" id=\"bytes_container\"></div>"
           "</div>"
           "</div>"
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</div>"
           "<script>"
           "function createByteRow(byteIndex, byteValue) {"
           "  const row = document.createElement('div');"
           "  row.className = 'byte-row';"
           "  const hexValue = '0x' + byteValue.toString(16).padStart(2, '0').toUpperCase();"
           "  const decValue = byteValue.toString().padStart(3, '0');"
           "  row.innerHTML = '<div class=\"byte-label\">Byte ' + byteIndex + ' HEX (' + hexValue + ') | DEC ' + decValue + '</div>';"
           "  "
           "  const bitsContainer = document.createElement('div');"
           "  bitsContainer.className = 'bits-container';"
           "  "
           "  for (let bit = 7; bit >= 0; bit--) {"
           "    const bitValue = (byteValue >> bit) & 1;"
           "    const checkbox = document.createElement('input');"
           "    checkbox.type = 'checkbox';"
           "    checkbox.className = 'bit-checkbox';"
           "    checkbox.id = 'byte' + byteIndex + '_bit' + bit;"
           "    checkbox.checked = bitValue === 1;"
           "    checkbox.disabled = true;"
           "    "
           "    const label = document.createElement('span');"
           "    label.className = 'bit-label';"
           "    label.textContent = bit;"
           "    "
           "    bitsContainer.appendChild(checkbox);"
           "    bitsContainer.appendChild(label);"
           "  }"
           "  "
           "  row.appendChild(bitsContainer);"
           "  return row;"
           "}"
           ""
           "function updateStatus() {"
           "  fetch('/api/status')"
           "    .then(r => {"
           "      if (!r.ok) {"
           "        throw new Error('HTTP ' + r.status);"
           "      }"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.input_assembly_100 && data.input_assembly_100.raw_bytes) {"
           "        const container = document.getElementById('bytes_container');"
           "        if (container) {"
           "          container.innerHTML = '';"
           "          for (let i = 0; i < data.input_assembly_100.raw_bytes.length; i++) {"
           "            const byteValue = data.input_assembly_100.raw_bytes[i];"
           "            const row = createByteRow(i, byteValue);"
           "            container.appendChild(row);"
           "          }"
           "        }"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Status update error:', err);"
           "    });"
           "}"
           "updateStatus();"
           "function updateNavigationBar() {"
           "  fetch('/api/sensor/enabled')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const navItems = document.querySelectorAll('nav li.sensor-nav-item');"
           "      navItems.forEach(item => {"
           "        if (item) {"
           "          item.style.display = data.enabled ? 'block' : 'none';"
           "        }"
           "      });"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to update navigation bar:', err);"
           "    });"
           "}"
           "updateNavigationBar();"
           "setInterval(updateStatus, 250);"
           "</script>"
           "</body>"
           "</html>";
}

const char *webui_get_ota_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>Firmware Update</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".navbar-nav li.sensor-nav-item { display: none; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".form-group { margin-bottom: 20px; }"
           "label { font-weight: 600; color: #555; display: block; margin-bottom: 5px; }"
           ".form-control { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; }"
           ".form-control:focus { border-color: #80bdff; outline: 0; box-shadow: 0 0 0 0.2rem rgba(0,123,255,0.25); }"
           "input[type=\"file\"] { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; cursor: pointer; }"
           "input[type=\"file\"]::-webkit-file-upload-button { padding: 6px 12px; margin-right: 12px; color: #fff; background-color: #007bff; border: 1px solid #007bff; border-radius: 4px; cursor: pointer; font-size: 14px; font-weight: 400; }"
           "input[type=\"file\"]::-webkit-file-upload-button:hover { background-color: #0069d9; border-color: #0062cc; }"
           "input[type=\"file\"]::file-selector-button { padding: 6px 12px; margin-right: 12px; color: #fff; background-color: #007bff; border: 1px solid #007bff; border-radius: 4px; cursor: pointer; font-size: 14px; font-weight: 400; }"
           "input[type=\"file\"]::file-selector-button:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".btn { display: inline-block; padding: 8px 16px; font-size: 14px; font-weight: 400; text-align: center; cursor: pointer; border: 1px solid transparent; border-radius: 4px; text-decoration: none; }"
           ".btn-primary { color: #fff; background-color: #007bff; border-color: #007bff; }"
           ".btn-primary:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".alert { position: relative; padding: 12px 20px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }"
           ".alert-success { color: #155724; background-color: #d4edda; border-color: #c3e6cb; }"
           ".alert-danger { color: #721c24; background-color: #f8d7da; border-color: #f5c6cb; }"
           ".alert-warning { color: #856404; background-color: #fff3cd; border-color: #ffeaa7; }"
           ".alert-info { color: #0c5460; background-color: #d1ecf1; border-color: #bee5eb; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\">Configuration</a></li>"
           "<li class=\"sensor-nav-item\"><a href=\"/vl53l1x\">VL53L1x</a></li>"
           "<li><a href=\"/inputassembly\">T->O</a></li>"
           "<li><a href=\"/outputassembly\">O->T</a></li>"
           "<li><a href=\"/ota\" class=\"active\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>Firmware Update</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div style=\"margin-bottom: 20px; padding: 12px; background-color: #f8f9fa; border-left: 4px solid #007bff; border-radius: 4px;\">"
           "<p style=\"margin: 0; color: #495057; font-size: 14px; line-height: 1.6;\">"
           "<strong>Over-The-Air (OTA) Firmware Update:</strong> Upload a new firmware binary file (.bin) to update the device firmware wirelessly. "
           "Select the firmware file and click \"Start Update\" to begin the process. The device will automatically reboot after a successful update. "
           "Ensure the firmware file is compatible with your device model and that you maintain a stable network connection during the update process."
           "</p>"
           "</div>"
           "<div class=\"form-group\">"
           "<label>Upload Firmware File (.bin)</label>"
           "<input type=\"file\" class=\"form-control\" id=\"firmware_file\" accept=\".bin\">"
           "</div>"
           "<div id=\"message\" class=\"alert\" style=\"display:none; margin-top:20px;\"></div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"startOTA()\" style=\"margin-top:20px;\">Start Update</button>"
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</div>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message');"
           "  msg.textContent = text;"
           "  msg.className = 'alert alert-' + type;"
           "  msg.style.display = 'block';"
           "}"
           "function startOTA() {"
           "  const fileInput = document.getElementById('firmware_file');"
           "  if (!fileInput) {"
           "    showMessage('Error: File input not found', 'danger');"
           "    return;"
           "  }"
           "  const file = fileInput.files[0];"
           "  if (!file) {"
           "    showMessage('Please select a firmware file', 'warning');"
           "    return;"
           "  }"
           "  const formData = new FormData();"
           "  formData.append('firmware', file);"
           "  showMessage('Uploading firmware...', 'info');"
           "  fetch('/api/ota/update', {"
           "    method: 'POST',"
           "    body: formData"
           "  })"
           "    .then(function(r) {"
           "      if (!r.ok) {"
           "        throw new Error('HTTP ' + r.status);"
           "      }"
           "      return r.json();"
           "    })"
           "    .then(function(data) {"
           "      if (data.status === 'ok') {"
           "        showMessage('Firmware uploaded successfully. Device will reboot in a few seconds...', 'success');"
           "        setTimeout(function() {"
           "          window.location.href = '/';"
           "        }, 5000);"
           "      } else {"
           "        showMessage('Firmware update failed: ' + (data.message || 'Unknown error'), 'danger');"
           "      }"
           "    })"
           "    .catch(function(err) {"
           "      showMessage('Error: ' + err.message, 'danger');"
           "    });"
           "}"
           "function updateNavigationBar() {"
           "  fetch('/api/sensor/enabled')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const navItems = document.querySelectorAll('nav li.sensor-nav-item');"
           "      navItems.forEach(item => {"
           "        if (item) {"
           "          item.style.display = data.enabled ? 'block' : 'none';"
           "        }"
           "      });"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to update navigation bar:', err);"
           "    });"
           "}"
           "updateNavigationBar();"
           "</script>"
           "</body>"
           "</html>";
}

