#include "webui_api.h"

const char *webui_get_index_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>VL53L1x Configuration</title>"
           "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">"
           "<style>"
           "body { padding: 20px; background-color: #f5f5f5; }"
           ".container { max-width: 800px; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }"
           "h1 { color: #333; margin-bottom: 30px; }"
           ".form-group { margin-bottom: 20px; }"
           "label { font-weight: 600; color: #555; }"
           ".btn-group { margin-top: 30px; }"
           "</style>"
           "</head>"
           "<body>"
           "<div class=\"container\">"
           "<h1>VL53L1x Sensor Configuration</h1>"
           "<form id=\"configForm\">"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Distance Mode</label>"
           "<select class=\"form-control\" id=\"distance_mode\" name=\"distance_mode\">"
           "<option value=\"1\">SHORT (<1.3m)</option>"
           "<option value=\"2\">LONG (<4m)</option>"
           "</select>"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Timing Budget (ms)</label>"
           "<select class=\"form-control\" id=\"timing_budget_ms\" name=\"timing_budget_ms\">"
           "<option value=\"15\">15</option>"
           "<option value=\"20\">20</option>"
           "<option value=\"33\">33</option>"
           "<option value=\"50\">50</option>"
           "<option value=\"100\">100</option>"
           "<option value=\"200\">200</option>"
           "<option value=\"500\">500</option>"
           "</select>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"form-group\">"
           "<label>Inter-Measurement Period (ms)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"inter_measurement_ms\" name=\"inter_measurement_ms\" min=\"15\" step=\"1\">"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>ROI X Size</label>"
           "<input type=\"number\" class=\"form-control\" id=\"roi_x_size\" name=\"roi_x_size\" min=\"4\" max=\"16\" value=\"16\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>ROI Y Size</label>"
           "<input type=\"number\" class=\"form-control\" id=\"roi_y_size\" name=\"roi_y_size\" min=\"4\" max=\"16\" value=\"16\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>ROI Center SPAD</label>"
           "<input type=\"number\" class=\"form-control\" id=\"roi_center_spad\" name=\"roi_center_spad\" min=\"0\" max=\"199\" value=\"199\">"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Offset (mm)</label>"
           "<div class=\"input-group\">"
           "<input type=\"number\" class=\"form-control\" id=\"offset_mm\" name=\"offset_mm\" min=\"-128\" max=\"127\" value=\"0\">"
           "<button type=\"button\" class=\"btn btn-secondary\" onclick=\"calibrateOffset()\">Calibrate</button>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Xtalk (cps)</label>"
           "<div class=\"input-group\">"
           "<input type=\"number\" class=\"form-control\" id=\"xtalk_cps\" name=\"xtalk_cps\" min=\"0\" max=\"65535\" value=\"0\">"
           "<button type=\"button\" class=\"btn btn-secondary\" onclick=\"calibrateXtalk()\">Calibrate</button>"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Signal Threshold (kcps)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"signal_threshold_kcps\" name=\"signal_threshold_kcps\" min=\"0\" max=\"65535\" value=\"1024\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Sigma Threshold (mm)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"sigma_threshold_mm\" name=\"sigma_threshold_mm\" min=\"0\" max=\"65535\" value=\"15\">"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>Threshold Low (mm)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"threshold_low_mm\" name=\"threshold_low_mm\" min=\"0\" max=\"4000\" value=\"0\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>Threshold High (mm)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"threshold_high_mm\" name=\"threshold_high_mm\" min=\"0\" max=\"4000\" value=\"0\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>Threshold Window</label>"
           "<select class=\"form-control\" id=\"threshold_window\" name=\"threshold_window\">"
           "<option value=\"0\">Below</option>"
           "<option value=\"1\">Above</option>"
           "<option value=\"2\">Out</option>"
           "<option value=\"3\">In</option>"
           "</select>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Interrupt Polarity</label>"
           "<select class=\"form-control\" id=\"interrupt_polarity\" name=\"interrupt_polarity\">"
           "<option value=\"0\">Active Low</option>"
           "<option value=\"1\">Active High</option>"
           "</select>"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>I2C Address</label>"
           "<input type=\"text\" class=\"form-control\" id=\"i2c_address\" name=\"i2c_address\" pattern=\"0x[0-9A-Fa-f]{2}\" value=\"0x29\">"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"btn-group\">"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveConfig()\">Save Configuration</button>"
           "<button type=\"button\" class=\"btn btn-secondary\" onclick=\"loadConfig()\">Load Current</button>"
           "<button type=\"button\" class=\"btn btn-warning\" onclick=\"resetConfig()\">Reset to Defaults</button>"
           "<a href=\"/status\" class=\"btn btn-info\">View Status</a>"
           "<a href=\"/ota\" class=\"btn btn-success\">OTA Update</a>"
           "</div>"
           "</form>"
           "<div id=\"message\" class=\"alert\" style=\"display:none; margin-top:20px;\"></div>"
           "</div>"
           "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message');"
           "  msg.textContent = text;"
           "  msg.className = 'alert alert-' + type;"
           "  msg.style.display = 'block';"
           "  setTimeout(() => msg.style.display = 'none', 5000);"
           "}"
           "function loadConfig() {"
           "  fetch('/api/config')"
           "    .then(r => r.json())"
           "    .then(data => {"
           "      document.getElementById('distance_mode').value = data.distance_mode;"
           "      document.getElementById('timing_budget_ms').value = data.timing_budget_ms;"
           "      document.getElementById('inter_measurement_ms').value = data.inter_measurement_ms;"
           "      document.getElementById('roi_x_size').value = data.roi_x_size;"
           "      document.getElementById('roi_y_size').value = data.roi_y_size;"
           "      document.getElementById('roi_center_spad').value = data.roi_center_spad;"
           "      document.getElementById('offset_mm').value = data.offset_mm;"
           "      document.getElementById('xtalk_cps').value = data.xtalk_cps;"
           "      document.getElementById('signal_threshold_kcps').value = data.signal_threshold_kcps;"
           "      document.getElementById('sigma_threshold_mm').value = data.sigma_threshold_mm;"
           "      document.getElementById('threshold_low_mm').value = data.threshold_low_mm;"
           "      document.getElementById('threshold_high_mm').value = data.threshold_high_mm;"
           "      document.getElementById('threshold_window').value = data.threshold_window;"
           "      document.getElementById('interrupt_polarity').value = data.interrupt_polarity;"
           "      document.getElementById('i2c_address').value = '0x' + data.i2c_address.toString(16).padStart(2, '0');"
           "      showMessage('Configuration loaded', 'success');"
           "    });"
           "}"
           "function saveConfig() {"
           "  const addr = document.getElementById('i2c_address').value;"
           "  const addrNum = parseInt(addr, 16);"
           "  const data = {"
           "    distance_mode: parseInt(document.getElementById('distance_mode').value),"
           "    timing_budget_ms: parseInt(document.getElementById('timing_budget_ms').value),"
           "    inter_measurement_ms: parseInt(document.getElementById('inter_measurement_ms').value),"
           "    roi_x_size: parseInt(document.getElementById('roi_x_size').value),"
           "    roi_y_size: parseInt(document.getElementById('roi_y_size').value),"
           "    roi_center_spad: parseInt(document.getElementById('roi_center_spad').value),"
           "    offset_mm: parseInt(document.getElementById('offset_mm').value),"
           "    xtalk_cps: parseInt(document.getElementById('xtalk_cps').value),"
           "    signal_threshold_kcps: parseInt(document.getElementById('signal_threshold_kcps').value),"
           "    sigma_threshold_mm: parseInt(document.getElementById('sigma_threshold_mm').value),"
           "    threshold_low_mm: parseInt(document.getElementById('threshold_low_mm').value),"
           "    threshold_high_mm: parseInt(document.getElementById('threshold_high_mm').value),"
           "    threshold_window: parseInt(document.getElementById('threshold_window').value),"
           "    interrupt_polarity: parseInt(document.getElementById('interrupt_polarity').value),"
           "    i2c_address: addrNum"
           "  };"
           "  fetch('/api/config', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify(data)"
           "  })"
           "    .then(r => r.json())"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage('Configuration saved successfully', 'success');"
           "      } else {"
           "        showMessage('Failed to save configuration', 'danger');"
           "      }"
           "    });"
           "}"
           "function resetConfig() {"
           "  if (confirm('Reset to default configuration?')) {"
           "    document.getElementById('distance_mode').value = 2;"
           "    document.getElementById('timing_budget_ms').value = 100;"
           "    document.getElementById('inter_measurement_ms').value = 100;"
           "    document.getElementById('roi_x_size').value = 16;"
           "    document.getElementById('roi_y_size').value = 16;"
           "    document.getElementById('roi_center_spad').value = 199;"
           "    document.getElementById('offset_mm').value = 0;"
           "    document.getElementById('xtalk_cps').value = 0;"
           "    document.getElementById('signal_threshold_kcps').value = 1024;"
           "    document.getElementById('sigma_threshold_mm').value = 15;"
           "    document.getElementById('threshold_low_mm').value = 0;"
           "    document.getElementById('threshold_high_mm').value = 0;"
           "    document.getElementById('threshold_window').value = 0;"
           "    document.getElementById('interrupt_polarity').value = 1;"
           "    document.getElementById('i2c_address').value = '0x29';"
           "    showMessage('Form reset to defaults', 'info');"
           "  }"
           "}"
           "function calibrateOffset() {"
           "  const dist = prompt('Enter target distance in mm (recommended: 100mm):', '100');"
           "  if (dist) {"
           "    fetch('/api/calibrate/offset', {"
           "      method: 'POST',"
           "      headers: { 'Content-Type': 'application/json' },"
           "      body: JSON.stringify({ target_distance_mm: parseInt(dist) })"
           "    })"
           "      .then(r => r.json())"
           "      .then(data => {"
           "        if (data.status === 'ok') {"
           "          document.getElementById('offset_mm').value = data.offset_mm;"
           "          showMessage('Offset calibration successful: ' + data.offset_mm + ' mm', 'success');"
           "        } else {"
           "          showMessage('Offset calibration failed', 'danger');"
           "        }"
           "      });"
           "  }"
           "}"
           "function calibrateXtalk() {"
           "  const dist = prompt('Enter target distance in mm (recommended: 600mm):', '600');"
           "  if (dist) {"
           "    fetch('/api/calibrate/xtalk', {"
           "      method: 'POST',"
           "      headers: { 'Content-Type': 'application/json' },"
           "      body: JSON.stringify({ target_distance_mm: parseInt(dist) })"
           "    })"
           "      .then(r => r.json())"
           "      .then(data => {"
           "        if (data.status === 'ok') {"
           "          document.getElementById('xtalk_cps').value = data.xtalk_cps;"
           "          showMessage('Xtalk calibration successful: ' + data.xtalk_cps + ' cps', 'success');"
           "        } else {"
           "          showMessage('Xtalk calibration failed', 'danger');"
           "        }"
           "      });"
           "  }"
           "}"
           "window.onload = function() { loadConfig(); };"
           "</script>"
           "</body>"
           "</html>";
}

const char *webui_get_status_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>VL53L1x Status</title>"
           "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">"
           "<style>"
           "body { padding: 20px; background-color: #f5f5f5; }"
           ".container { max-width: 900px; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }"
           "h1 { color: #333; margin-bottom: 30px; }"
           ".status-card { border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin-bottom: 20px; }"
           ".status-value { font-size: 24px; font-weight: bold; color: #007bff; }"
           "</style>"
           "</head>"
           "<body>"
           "<div class=\"container\">"
           "<h1>VL53L1x Sensor Status</h1>"
           "<div class=\"status-card\">"
           "<h3>Current Readings</h3>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<p><strong>Distance:</strong> <span class=\"status-value\" id=\"distance\">-</span> mm</p>"
           "<p><strong>Status:</strong> <span id=\"status\">-</span></p>"
           "<p><strong>Ambient:</strong> <span id=\"ambient\">-</span> kcps</p>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<p><strong>Signal per SPAD:</strong> <span id=\"sig_per_spad\">-</span> kcps/SPAD</p>"
           "<p><strong>Number of SPADs:</strong> <span id=\"num_spads\">-</span></p>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"status-card\">"
           "<h3>Configuration</h3>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<p><strong>Distance Mode:</strong> <span id=\"config_distance_mode\">-</span></p>"
           "<p><strong>Timing Budget:</strong> <span id=\"config_timing_budget\">-</span> ms</p>"
           "<p><strong>Inter-Measurement:</strong> <span id=\"config_inter_measurement\">-</span> ms</p>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"btn-group\">"
           "<a href=\"/\" class=\"btn btn-primary\">Configuration</a>"
           "<button class=\"btn btn-secondary\" onclick=\"location.reload()\">Refresh</button>"
           "</div>"
           "</div>"
           "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>"
           "<script>"
           "function updateStatus() {"
           "  fetch('/api/status')"
           "    .then(r => r.json())"
           "    .then(data => {"
           "      document.getElementById('distance').textContent = data.distance_mm;"
           "      document.getElementById('status').textContent = data.status === 0 ? 'Valid' : 'Error ' + data.status;"
           "      document.getElementById('ambient').textContent = data.ambient_kcps;"
           "      document.getElementById('sig_per_spad').textContent = data.sig_per_spad_kcps;"
           "      document.getElementById('num_spads').textContent = data.num_spads;"
           "      const mode = data.config.distance_mode === 1 ? 'SHORT' : 'LONG';"
           "      document.getElementById('config_distance_mode').textContent = mode;"
           "      document.getElementById('config_timing_budget').textContent = data.config.timing_budget_ms;"
           "      document.getElementById('config_inter_measurement').textContent = data.config.inter_measurement_ms;"
           "    });"
           "}"
           "updateStatus();"
           "setInterval(updateStatus, 1000);"
           "</script>"
           "</body>"
           "</html>";
}

const char *webui_get_ota_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>OTA Update</title>"
           "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">"
           "<style>"
           "body { padding: 20px; background-color: #f5f5f5; }"
           ".container { max-width: 600px; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }"
           "h1 { color: #333; margin-bottom: 30px; }"
           ".progress { margin-top: 20px; height: 30px; }"
           "</style>"
           "</head>"
           "<body>"
           "<div class=\"container\">"
           "<h1>OTA Firmware Update</h1>"
           "<div class=\"form-group\">"
           "<label>Upload Firmware File (.bin)</label>"
           "<input type=\"file\" class=\"form-control\" id=\"firmware_file\" accept=\".bin\">"
           "</div>"
           "<button class=\"btn btn-primary\" onclick=\"startOTA()\">Start Update</button>"
           "<div id=\"progress\" style=\"display:none; margin-top:20px;\">"
           "<div class=\"progress\">"
           "<div class=\"progress-bar\" role=\"progressbar\" id=\"progress_bar\" style=\"width:0%\">0%</div>"
           "</div>"
           "<p id=\"status_text\">Preparing...</p>"
           "</div>"
           "<div id=\"message\" class=\"alert\" style=\"display:none; margin-top:20px;\"></div>"
           "<div class=\"btn-group\" style=\"margin-top:20px;\">"
           "<a href=\"/\" class=\"btn btn-secondary\">Back to Config</a>"
           "</div>"
           "</div>"
           "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message');"
           "  msg.textContent = text;"
           "  msg.className = 'alert alert-' + type;"
           "  msg.style.display = 'block';"
           "}"
           "function startOTA() {"
           "  const fileInput = document.getElementById('firmware_file');"
           "  const file = fileInput.files[0];"
           "  if (!file) {"
           "    showMessage('Please select a firmware file', 'warning');"
           "    return;"
           "  }"
           "  document.getElementById('progress').style.display = 'block';"
           "  document.getElementById('message').style.display = 'none';"
           "  const formData = new FormData();"
           "  formData.append('firmware', file);"
           "  fetch('/api/ota/update', {"
           "    method: 'POST',"
           "    body: formData"
           "  })"
           "    .then(async r => {"
           "      if (!r.ok) {"
           "        const errorText = await r.text();"
           "        let errorData;"
           "        try {"
           "          errorData = JSON.parse(errorText);"
           "        } catch (e) {"
           "          errorData = { message: 'HTTP ' + r.status + ': ' + errorText };"
           "        }"
           "        throw new Error(errorData.message || 'HTTP ' + r.status);"
           "      }"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage('OTA update started. Device will reboot when complete.', 'success');"
           "        pollOTAStatus();"
           "      } else {"
           "        showMessage('OTA update failed: ' + (data.message || 'Unknown error'), 'danger');"
           "        document.getElementById('progress').style.display = 'none';"
           "      }"
           "    })"
           "    .catch(err => {"
           "      showMessage('Error: ' + err.message, 'danger');"
           "      document.getElementById('progress').style.display = 'none';"
           "      console.error('OTA update error:', err);"
           "    });"
           "}"
           "function pollOTAStatus() {"
           "  const interval = setInterval(() => {"
           "    fetch('/api/ota/status')"
           "      .then(r => r.json())"
           "      .then(data => {"
           "        const progress = data.progress || 0;"
           "        document.getElementById('progress_bar').style.width = progress + '%';"
           "        document.getElementById('progress_bar').textContent = progress + '%';"
           "        document.getElementById('status_text').textContent = data.message || 'Updating...';"
           "        if (data.status === 'complete' || data.status === 'error') {"
           "          clearInterval(interval);"
           "          if (data.status === 'complete') {"
           "            showMessage('Update complete. Device will reboot.', 'success');"
           "          } else {"
           "            showMessage('Update failed: ' + (data.message || 'Unknown error'), 'danger');"
           "          }"
           "        }"
           "      });"
           "  }, 1000);"
           "}"
           "</script>"
           "</body>"
           "</html>";
}

