#include "webui_api.h"

const char *webui_get_index_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>VL53L1x Configuration</title>"
           "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">"
           "<style>"
           "body { padding: 0; background-color: #f5f5f5; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; }"
           "h1 { color: #333; margin-bottom: 30px; }"
           ".form-group { margin-bottom: 20px; }"
           "label { font-weight: 600; color: #555; }"
           ".btn-group { margin-top: 30px; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\" class=\"active\">Configuration</a></li>"
           "<li><a href=\"/status\">Status</a></li>"
           "<li><a href=\"/ota\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<h1>VL53L1x Sensor Configuration</h1>"
           "<form id=\"configForm\">"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Distance Mode</label>"
           "<select class=\"form-control\" id=\"distance_mode\" name=\"distance_mode\">"
           "<option value=\"1\">SHORT (<1.3m)</option>"
           "<option value=\"2\">LONG (<4m)</option>"
           "</select>"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Timing Budget (ms)</label>"
           "<select class=\"form-control\" id=\"timing_budget_ms\" name=\"timing_budget_ms\">"
           "<option value=\"15\">15</option>"
           "<option value=\"20\">20</option>"
           "<option value=\"33\">33</option>"
           "<option value=\"50\">50</option>"
           "<option value=\"100\">100</option>"
           "<option value=\"200\">200</option>"
           "<option value=\"500\">500</option>"
           "</select>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"form-group\">"
           "<label>Inter-Measurement Period (ms)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"inter_measurement_ms\" name=\"inter_measurement_ms\" min=\"15\" step=\"1\">"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>ROI X Size</label>"
           "<input type=\"number\" class=\"form-control\" id=\"roi_x_size\" name=\"roi_x_size\" min=\"4\" max=\"16\" value=\"16\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>ROI Y Size</label>"
           "<input type=\"number\" class=\"form-control\" id=\"roi_y_size\" name=\"roi_y_size\" min=\"4\" max=\"16\" value=\"16\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>ROI Center SPAD</label>"
           "<input type=\"number\" class=\"form-control\" id=\"roi_center_spad\" name=\"roi_center_spad\" min=\"0\" max=\"199\" value=\"199\">"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Offset (mm)</label>"
           "<div class=\"input-group\">"
           "<input type=\"number\" class=\"form-control\" id=\"offset_mm\" name=\"offset_mm\" min=\"-128\" max=\"127\" value=\"0\">"
           "<button type=\"button\" class=\"btn btn-secondary\" onclick=\"calibrateOffset()\">Calibrate</button>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Xtalk (cps)</label>"
           "<div class=\"input-group\">"
           "<input type=\"number\" class=\"form-control\" id=\"xtalk_cps\" name=\"xtalk_cps\" min=\"0\" max=\"65535\" value=\"0\">"
           "<button type=\"button\" class=\"btn btn-secondary\" onclick=\"calibrateXtalk()\">Calibrate</button>"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Signal Threshold (kcps)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"signal_threshold_kcps\" name=\"signal_threshold_kcps\" min=\"0\" max=\"65535\" value=\"1024\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Sigma Threshold (mm)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"sigma_threshold_mm\" name=\"sigma_threshold_mm\" min=\"0\" max=\"65535\" value=\"15\">"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>Threshold Low (mm)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"threshold_low_mm\" name=\"threshold_low_mm\" min=\"0\" max=\"4000\" value=\"0\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>Threshold High (mm)</label>"
           "<input type=\"number\" class=\"form-control\" id=\"threshold_high_mm\" name=\"threshold_high_mm\" min=\"0\" max=\"4000\" value=\"0\">"
           "</div>"
           "</div>"
           "<div class=\"col-md-4\">"
           "<div class=\"form-group\">"
           "<label>Threshold Window</label>"
           "<select class=\"form-control\" id=\"threshold_window\" name=\"threshold_window\">"
           "<option value=\"0\">Below</option>"
           "<option value=\"1\">Above</option>"
           "<option value=\"2\">Out</option>"
           "<option value=\"3\">In</option>"
           "</select>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>Interrupt Polarity</label>"
           "<select class=\"form-control\" id=\"interrupt_polarity\" name=\"interrupt_polarity\">"
           "<option value=\"0\">Active Low</option>"
           "<option value=\"1\">Active High</option>"
           "</select>"
           "</div>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<div class=\"form-group\">"
           "<label>I2C Address</label>"
           "<input type=\"text\" class=\"form-control\" id=\"i2c_address\" name=\"i2c_address\" pattern=\"0x[0-9A-Fa-f]{2}\" value=\"0x29\">"
           "</div>"
           "</div>"
           "</div>"
           "<div style=\"display: flex; justify-content: space-between; gap: 15px; margin-top: 30px;\">"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveConfig()\" style=\"flex: 1;\">Save Configuration</button>"
           "<button type=\"button\" class=\"btn btn-secondary\" onclick=\"loadConfig()\" style=\"flex: 1;\">Load Current</button>"
           "<button type=\"button\" class=\"btn btn-warning\" onclick=\"resetConfig()\" style=\"flex: 1;\">Reset to Defaults</button>"
           "</div>"
           "</form>"
           "<div id=\"message\" class=\"alert\" style=\"display:none; margin-top:20px;\"></div>"
           "</div>"
           "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message');"
           "  msg.textContent = text;"
           "  msg.className = 'alert alert-' + type;"
           "  msg.style.display = 'block';"
           "  setTimeout(() => msg.style.display = 'none', 5000);"
           "}"
           "function loadConfig() {"
           "  fetch('/api/config')"
           "    .then(r => r.json())"
           "    .then(data => {"
           "      document.getElementById('distance_mode').value = data.distance_mode;"
           "      document.getElementById('timing_budget_ms').value = data.timing_budget_ms;"
           "      document.getElementById('inter_measurement_ms').value = data.inter_measurement_ms;"
           "      document.getElementById('roi_x_size').value = data.roi_x_size;"
           "      document.getElementById('roi_y_size').value = data.roi_y_size;"
           "      document.getElementById('roi_center_spad').value = data.roi_center_spad;"
           "      document.getElementById('offset_mm').value = data.offset_mm;"
           "      document.getElementById('xtalk_cps').value = data.xtalk_cps;"
           "      document.getElementById('signal_threshold_kcps').value = data.signal_threshold_kcps;"
           "      document.getElementById('sigma_threshold_mm').value = data.sigma_threshold_mm;"
           "      document.getElementById('threshold_low_mm').value = data.threshold_low_mm;"
           "      document.getElementById('threshold_high_mm').value = data.threshold_high_mm;"
           "      document.getElementById('threshold_window').value = data.threshold_window;"
           "      document.getElementById('interrupt_polarity').value = data.interrupt_polarity;"
           "      document.getElementById('i2c_address').value = '0x' + data.i2c_address.toString(16).padStart(2, '0');"
           "      showMessage('Configuration loaded', 'success');"
           "    });"
           "}"
           "function saveConfig() {"
           "  const addr = document.getElementById('i2c_address').value;"
           "  const addrNum = parseInt(addr, 16);"
           "  const data = {"
           "    distance_mode: parseInt(document.getElementById('distance_mode').value),"
           "    timing_budget_ms: parseInt(document.getElementById('timing_budget_ms').value),"
           "    inter_measurement_ms: parseInt(document.getElementById('inter_measurement_ms').value),"
           "    roi_x_size: parseInt(document.getElementById('roi_x_size').value),"
           "    roi_y_size: parseInt(document.getElementById('roi_y_size').value),"
           "    roi_center_spad: parseInt(document.getElementById('roi_center_spad').value),"
           "    offset_mm: parseInt(document.getElementById('offset_mm').value),"
           "    xtalk_cps: parseInt(document.getElementById('xtalk_cps').value),"
           "    signal_threshold_kcps: parseInt(document.getElementById('signal_threshold_kcps').value),"
           "    sigma_threshold_mm: parseInt(document.getElementById('sigma_threshold_mm').value),"
           "    threshold_low_mm: parseInt(document.getElementById('threshold_low_mm').value),"
           "    threshold_high_mm: parseInt(document.getElementById('threshold_high_mm').value),"
           "    threshold_window: parseInt(document.getElementById('threshold_window').value),"
           "    interrupt_polarity: parseInt(document.getElementById('interrupt_polarity').value),"
           "    i2c_address: addrNum"
           "  };"
           "  fetch('/api/config', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify(data)"
           "  })"
           "    .then(r => r.json())"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage('Configuration saved successfully', 'success');"
           "      } else {"
           "        showMessage('Failed to save configuration', 'danger');"
           "      }"
           "    });"
           "}"
           "function resetConfig() {"
           "  if (confirm('Reset to default configuration?')) {"
           "    document.getElementById('distance_mode').value = 2;"
           "    document.getElementById('timing_budget_ms').value = 100;"
           "    document.getElementById('inter_measurement_ms').value = 100;"
           "    document.getElementById('roi_x_size').value = 16;"
           "    document.getElementById('roi_y_size').value = 16;"
           "    document.getElementById('roi_center_spad').value = 199;"
           "    document.getElementById('offset_mm').value = 0;"
           "    document.getElementById('xtalk_cps').value = 0;"
           "    document.getElementById('signal_threshold_kcps').value = 1024;"
           "    document.getElementById('sigma_threshold_mm').value = 15;"
           "    document.getElementById('threshold_low_mm').value = 0;"
           "    document.getElementById('threshold_high_mm').value = 0;"
           "    document.getElementById('threshold_window').value = 0;"
           "    document.getElementById('interrupt_polarity').value = 1;"
           "    document.getElementById('i2c_address').value = '0x29';"
           "    showMessage('Form reset to defaults', 'info');"
           "  }"
           "}"
           "function calibrateOffset() {"
           "  const dist = prompt('Enter target distance in mm (recommended: 100mm):', '100');"
           "  if (dist) {"
           "    fetch('/api/calibrate/offset', {"
           "      method: 'POST',"
           "      headers: { 'Content-Type': 'application/json' },"
           "      body: JSON.stringify({ target_distance_mm: parseInt(dist) })"
           "    })"
           "      .then(r => r.json())"
           "      .then(data => {"
           "        if (data.status === 'ok') {"
           "          document.getElementById('offset_mm').value = data.offset_mm;"
           "          showMessage('Offset calibration successful: ' + data.offset_mm + ' mm', 'success');"
           "        } else {"
           "          showMessage('Offset calibration failed', 'danger');"
           "        }"
           "      });"
           "  }"
           "}"
           "function calibrateXtalk() {"
           "  const dist = prompt('Enter target distance in mm (recommended: 600mm):', '600');"
           "  if (dist) {"
           "    fetch('/api/calibrate/xtalk', {"
           "      method: 'POST',"
           "      headers: { 'Content-Type': 'application/json' },"
           "      body: JSON.stringify({ target_distance_mm: parseInt(dist) })"
           "    })"
           "      .then(r => r.json())"
           "      .then(data => {"
           "        if (data.status === 'ok') {"
           "          document.getElementById('xtalk_cps').value = data.xtalk_cps;"
           "          showMessage('Xtalk calibration successful: ' + data.xtalk_cps + ' cps', 'success');"
           "        } else {"
           "          showMessage('Xtalk calibration failed', 'danger');"
           "        }"
           "      });"
           "  }"
           "}"
           "window.onload = function() { loadConfig(); };"
           "</script>"
           "</div>"
           "<footer style=\"text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666;\">Beta 1.1</footer>"
           "</div>"
           "</body>"
           "</html>";
}

const char *webui_get_status_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>VL53L1x Status</title>"
           "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">"
           "<script src=\"https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js\"></script>"
           "<style>"
           "body { padding: 0; background-color: #f5f5f5; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 900px; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; }"
           "h1 { color: #333; margin-bottom: 30px; }"
           ".status-card { border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin-bottom: 20px; }"
           ".status-value { font-size: 24px; font-weight: bold; color: #007bff; }"
           "#distanceChart { max-height: 400px; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\">Configuration</a></li>"
           "<li><a href=\"/status\" class=\"active\">Status</a></li>"
           "<li><a href=\"/ota\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<h1>VL53L1x Sensor Status</h1>"
           "<div class=\"status-card\">"
           "<h3>Current Readings</h3>"
           "<div class=\"row\">"
           "<div class=\"col-md-6\">"
           "<p><strong>Distance:</strong> <span class=\"status-value\" id=\"distance\">-</span> mm</p>"
           "<p><strong>Status:</strong> <span id=\"status\">-</span></p>"
           "<p><strong>Ambient:</strong> <span id=\"ambient\">-</span> kcps</p>"
           "</div>"
           "<div class=\"col-md-6\">"
           "<p><strong>Signal per SPAD:</strong> <span id=\"sig_per_spad\">-</span> kcps/SPAD</p>"
           "<p><strong>Number of SPADs:</strong> <span id=\"num_spads\">-</span></p>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"status-card\">"
           "<h3>Distance Over Time</h3>"
           "<canvas id=\"distanceChart\"></canvas>"
           "</div>"
           "</div>"
           "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>"
           "<script>"
           "let distanceChart = null;"
           "let chartData = {"
           "  labels: [],"
           "  distances: []"
           "};"
           "const maxDataPoints = 60;"
           ""
           "function formatTime(date) {"
           "  const hours = date.getHours().toString().padStart(2, '0');"
           "  const minutes = date.getMinutes().toString().padStart(2, '0');"
           "  const seconds = date.getSeconds().toString().padStart(2, '0');"
           "  return hours + ':' + minutes + ':' + seconds;"
           "}"
           ""
           "function initChart() {"
           "  const ctx = document.getElementById('distanceChart').getContext('2d');"
           "  distanceChart = new Chart(ctx, {"
           "    type: 'line',"
           "    data: {"
           "      labels: chartData.labels,"
           "      datasets: [{"
           "        label: 'Distance (mm)',"
           "        data: chartData.distances,"
           "        borderColor: '#007bff',"
           "        backgroundColor: 'rgba(0, 123, 255, 0.1)',"
           "        borderWidth: 2,"
           "        fill: true,"
           "        tension: 0.4"
           "      }]"
           "    },"
           "    options: {"
           "      responsive: true,"
           "      maintainAspectRatio: true,"
           "      scales: {"
           "        x: {"
           "          title: {"
           "            display: true,"
           "            text: 'Time'"
           "          }"
           "        },"
           "        y: {"
           "          title: {"
           "            display: true,"
           "            text: 'Distance (mm)'"
           "          },"
           "          min: 0,"
           "          max: 4000"
           "        }"
           "      },"
           "      plugins: {"
           "        legend: {"
           "          display: true"
           "        }"
           "      }"
           "    }"
           "  });"
           "}"
           ""
           "function updateChart(distance, timestamp) {"
           "  const timeLabel = formatTime(timestamp);"
           "  chartData.labels.push(timeLabel);"
           "  chartData.distances.push(distance);"
           ""
           "  if (chartData.labels.length > maxDataPoints) {"
           "    chartData.labels.shift();"
           "    chartData.distances.shift();"
           "  }"
           ""
           "  if (distanceChart) {"
           "    distanceChart.update('none');"
           "  }"
           "}"
           ""
           "function updateStatus() {"
           "  fetch('/api/status')"
           "    .then(r => r.json())"
           "    .then(data => {"
           "      document.getElementById('distance').textContent = data.distance_mm;"
           "      document.getElementById('status').textContent = data.status === 0 ? 'Valid' : 'Error ' + data.status;"
           "      document.getElementById('ambient').textContent = data.ambient_kcps;"
           "      document.getElementById('sig_per_spad').textContent = data.sig_per_spad_kcps;"
           "      document.getElementById('num_spads').textContent = data.num_spads;"
           "      updateChart(data.distance_mm, new Date());"
           "    });"
           "}"
           "initChart();"
           "updateStatus();"
           "setInterval(updateStatus, 250);"
           "</script>"
           "</div>"
           "<footer style=\"text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666;\">Beta 1.1</footer>"
           "</div>"
           "</body>"
           "</html>";
}

const char *webui_get_ota_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>Firmware Update</title>"
           "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">"
           "<style>"
           "body { padding: 0; background-color: #f5f5f5; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 600px; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; }"
           "h1 { color: #333; margin-bottom: 30px; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\">Configuration</a></li>"
           "<li><a href=\"/status\">Status</a></li>"
           "<li><a href=\"/ota\" class=\"active\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<h1>Firmware Update</h1>"
           "<div class=\"mb-3\">"
           "<label class=\"form-label\">Upload Firmware File (.bin)</label>"
           "<input type=\"file\" class=\"form-control\" id=\"firmware_file\" accept=\".bin\">"
           "</div>"
           "<div id=\"message\" class=\"alert\" style=\"display:none; margin-top:20px;\"></div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"startOTA()\" style=\"margin-top:20px;\">Start Update</button>"
           "</div>"
           "<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message');"
           "  msg.textContent = text;"
           "  msg.className = 'alert alert-' + type;"
           "  msg.style.display = 'block';"
           "}"
           "function startOTA() {"
           "  const fileInput = document.getElementById('firmware_file');"
           "  if (!fileInput) {"
           "    showMessage('Error: File input not found', 'danger');"
           "    return;"
           "  }"
           "  const file = fileInput.files[0];"
           "  if (!file) {"
           "    showMessage('Please select a firmware file', 'warning');"
           "    return;"
           "  }"
           "  const formData = new FormData();"
           "  formData.append('firmware', file);"
           "  showMessage('Uploading firmware...', 'info');"
           "  fetch('/api/ota/update', {"
           "    method: 'POST',"
           "    body: formData"
           "  })"
           "    .then(function(r) {"
           "      if (!r.ok) {"
           "        throw new Error('HTTP ' + r.status);"
           "      }"
           "      return r.json();"
           "    })"
           "    .then(function(data) {"
           "      if (data.status === 'ok') {"
           "        showMessage('Firmware uploaded successfully. Device will reboot in a few seconds...', 'success');"
           "        setTimeout(function() {"
           "          window.location.href = '/';"
           "        }, 5000);"
           "      } else {"
           "        showMessage('Firmware update failed: ' + (data.message || 'Unknown error'), 'danger');"
           "      }"
           "    })"
           "    .catch(function(err) {"
           "      showMessage('Error: ' + err.message, 'danger');"
           "    });"
           "}"
           "</script>"
           "</div>"
           "<footer style=\"text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666;\">Beta 1.1</footer>"
           "</div>"
           "</body>"
           "</html>";
}

